{{ if (include "anyIntAuth" . | toJson) }}
{{ $helmName := include "helm.name" . }}
{{ $helmChart := include "helm.chart" . }}
{{- range $i := .Values.notaries }}
{{- if $i.auth }}
{{- if not $i.auth.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $i.name }}-host-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $helmName }}
    helm.sh/chart: {{ $helmChart }}
    app.kubernetes.io/instance: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
data:
  cred.yaml: {{ include "getIntAuth" $i.auth | b64enc }}
---
{{ end -}}
{{ end }}
{{ end }}
{{ end }}