# configure connaisseur deployment
deployment:
  replicasCount: 3
  image: securesystemsengineering/connaisseur:v2.0.0
  helmHookImage: securesystemsengineering/connaisseur:helm-hook-v1.0
  imagePullPolicy: Always
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

# configure connaisseur service
service:
  type: ClusterIP
  port: 443

# configure access to the notary server
notaries:
# public notary form dockerhub
- name: dockerhub
  host: notary.docker.io
  rootKeys:
  - name: library
    key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOXYta5TgdCwXTCnLU09W5T4M4r9f
      QQrqJuADP6U7g5r9ICgPSmZuRHP/1AYUfOQW3baveKsT969EfELKj1lfCA==
      -----END PUBLIC KEY-----
# additional sample configuration
# - name: sample-notary  # name for referencing in the image policy
#   host: notary.sample.org  # host address, where to reach the notary
#   rootKeys:  # public root keys, used fo rsignature erification
#   - name: default  # name for referencing in the image policy
#     key: |  # key in PEM format
#       -----BEGIN PUBLIC KEY-----
#       ...
#       -----END PUBLIC KEY-----
#   selfsignedCert: |  # selfsigned certificate in PEM format
#     -----BEGIN CERTIFICATE-----
#     -----END CERTIFICATE-----
#   rootKeys:
#   - name: library
#     key: |
#       -----BEGIN PUBLIC KEY-----
#       -----END PUBLIC KEY-----
#   auth:
#     secretName: harbor-creds

# the image policy, which defines all repositories that need to be
# verified. more detail in the git repo README.md
policy:
- pattern: "*:*"
  verify: true
  notary: dockerhub
  key: library
- pattern: "docker.io/connytest/*:*"
  verify: true
  notary: dockerhub
  key: connytest
- pattern: "docker.io/securesystemsengineering/connaisseur:*"
  verify: false

# in detection mode, deployment will not be denied, but only prompted
# and logged. This allows testing the functionality without
# interrupting operation.
detection_mode: false

# debug: true
